language: go
go:
    - 1.2
install:
    - export PATH=$PATH:$HOME/gopath/bin
    - go get github.com/kr/godep
    - godep get
    - go get github.com/dictybase/testchado
branches:
    only:
      - develop
script:
      - go test ./...
before_install: sudo apt-get install mercurial
